# Generated by Django 3.1.7 on 2021-03-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20210312_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracker',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='type',
        ),
        migrations.AddField(
            model_name='tracker',
            name='type',
            field=models.ManyToManyField(blank=True, null=True, related_name='trackers', to='webapp.Type'),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
