# Generated by Django 3.1.7 on 2021-03-17 11:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20210312_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='title',
            field=models.CharField(max_length=3000, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
