# Generated by Django 3.1.7 on 2021-03-17 12:04

from django.db import migrations, models
import webapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20210317_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='title',
            field=models.CharField(max_length=3000, validators=[webapp.validators.MinLengthValidator(5)]),
        ),
    ]
