# Generated by Django 3.1.7 on 2021-03-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20210317_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='description',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
    ]
