# Generated by Django 3.1.7 on 2021-03-26 12:31

from django.db import migrations, models
import webapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20210317_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ad', models.DateTimeField(auto_now_add=True)),
                ('update_ad', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=3000, null=True)),
                ('date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'db_table': 'projects',
            },
        ),
        migrations.AlterField(
            model_name='tracker',
            name='description',
            field=models.TextField(blank=True, max_length=3000, null=True, validators=[webapp.validators.MinLengthValidator(5)]),
        ),
    ]
