# Generated by Django 3.1.7 on 2021-03-26 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20210326_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_trackers', to='webapp.project'),
        ),
    ]
