# Generated by Django 3.1.7 on 2021-03-29 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_auto_20210329_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='project',
            field=models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_trackers', to='webapp.project'),
        ),
    ]
