# Generated by Django 3.1.7 on 2021-04-08 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_auto_20210329_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='type',
            field=models.ManyToManyField(related_name='trackers', to='webapp.Type'),
        ),
    ]
